### ISSUE TITLE
A dependency is missing on new installation?

### ISSUE THREAD

**Issue by tute** [thoughtbot/parity#91]
I recently uninstalled all gems in my system. After running `gem install parity` and trying to use it in projects where it was working before, I get:

```
% development restore production
/Users/tutec/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- git (LoadError)
        from /Users/tutec/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/tutec/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/parity-0.9.3/lib/parity.rb:7:in `<top (required)>'
        from /Users/tutec/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/tutec/.rbenv/versions/2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/tutec/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/parity-0.9.3/bin/development:3:in `<top (required)>'
        from /Users/tutec/.rbenv/versions/2.3.0/bin/development:22:in `load'
        from /Users/tutec/.rbenv/versions/2.3.0/bin/development:22:in `<main>'
```

Is there a missing dependency? Thank you!

**Comment by tute** [comment]
After running `gem install git` it started working. I think we need to add `git` as a development dependency in `parity.gemspec`.

**Comment by geoffharcourt** [comment]
Blerg, @tute, I'm sorry about that.

I'm going to be removing the executable from the Rubygems-installed gem shortly and recommending that users install the package from Homebrew or releases in the next week or so.
