### ISSUE TITLE
`development restore-from production` command failed

### ISSUE THREAD

**Issue by JuanitoFatas** [thoughtbot/parity#93]
Parity 0.9.3

```
$ development restore-from production
(erb):89:in `<main>': uninitialized constant Rails (NameError)
	from /usr/local/Cellar/parity/0.9.3/lib/ruby/lib/ruby/2.2.0/erb.rb:863:in `eval'
	from /usr/local/Cellar/parity/0.9.3/lib/ruby/lib/ruby/2.2.0/erb.rb:863:in `result'
	from /usr/local/Cellar/parity/0.9.3/lib/app/lib/parity/backup.rb:76:in `parsed_database_yml'
	from /usr/local/Cellar/parity/0.9.3/lib/app/lib/parity/backup.rb:68:in `development_db'
	from /usr/local/Cellar/parity/0.9.3/lib/app/lib/parity/backup.rb:42:in `drop_development_database'
	from /usr/local/Cellar/parity/0.9.3/lib/app/lib/parity/backup.rb:37:in `restore_to_development'
	from /usr/local/Cellar/parity/0.9.3/lib/app/lib/parity/backup.rb:15:in `restore'
	from /usr/local/Cellar/parity/0.9.3/lib/app/lib/parity/environment.rb:68:in `restore'
	from /usr/local/Cellar/parity/0.9.3/lib/app/lib/parity/environment.rb:23:in `run_command'
	from /usr/local/Cellar/parity/0.9.3/lib/app/lib/parity/environment.rb:12:in `run'
	from /usr/local/Cellar/parity/0.9.3/lib/app/bin/development:8:in `<main>'
```

**Comment by geoffharcourt** [comment]
@JuanitoFatas can you install v0.10.0 and test on Ubuntu? I've removed external dependencies, so I expect your issues should be resolved.
